version: "3"
services:
  streamer:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./photos:/opt/streamer/test-photos:ro
    environment:
      LOG_LEVEL: DEBUG
      STORAGE: test-photos
      DELAY: 0.01
